export enum HeroesActionTypes{
  REQUEST_HEROES= 'REQUEST_HEROES',
  REQUEST_HEROES_SUCCESS= 'REQUEST_HEROES_SUCCESS',
  REQUEST_HEROES_ERROR= 'REQUEST_HEROES_ERROR'
}

export enum HeroActionTypes{
  REQUEST_HERO= 'REQUEST_HERO',
  REQUEST_HERO_SUCCESS= 'REQUEST_HERO_SUCCESS',
  REQUEST_HERO_ERROR= 'REQUEST_HERO_ERROR'
}
