export enum HeroesActionTypes{
  REQUEST_HEROES_START= 'REQUEST_HEROES_START',
  REQUEST_HEROES= 'REQUEST_HEROES',
  REQUEST_HEROES_SUCCESS= 'REQUEST_HEROES_SUCCESS',
}

export enum HeroActionTypes{
  REQUEST_HERO_START= 'REQUEST_HERO_START',
  REQUEST_HERO= 'REQUEST_HERO',
  REQUEST_HERO_SUCCESS= 'REQUEST_HERO_SUCCESS',
}
