export enum HeroesActionTypes{
  ON_REQUEST_HEROES_START= 'REQUEST_HEROES_START',
  ON_REQUEST_HEROES= 'REQUEST_HEROES',
  ON_REQUEST_HEROES_SUCCESS= 'REQUEST_HEROES_SUCCESS',
}

export enum HeroActionTypes{
  ON_REQUEST_HERO_START= 'REQUEST_HERO_START',
  ON_REQUEST_HERO= 'REQUEST_HERO',
  ON_REQUEST_HERO_SUCCESS= 'REQUEST_HERO_SUCCESS',
}
